src/survivalguide/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from rest_framework.routers import DefaultRouter

ROUTER = DefaultRouter()

urlpatterns = [
    path('api/', include(ROUTER.urls)),
    path('', RedirectView.as_view(pattern_name='talklists:list'), name='home'),
    path('talks/', include('talk.urls', namespace='talks')),
    path('talklist/', include('talklist.urls', namespace='talklists')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

# TODO: Implement 2FA & update corresponding Cover letter
# TODO: Implement TBA using django-allauth & update corresponding Cover letter

src/talk/urls.py
from django.urls import path

from rest_framework.urlpatterns import format_suffix_patterns

from survivalguide.urls import ROUTER
from talk.views import TalkViewSet
from talklist.views import TalkListDeleteTalkView

app_name = 'talks'

ROUTER.register(r'talks', TalkViewSet, base_name='talk')

urlpatterns = [
    path('talk/<int:talklist_pk>/<int:pk>/delete/', TalkListDeleteTalkView.as_view(), name='delete_talk'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/talklist/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path

from rest_framework.urlpatterns import format_suffix_patterns

from survivalguide.urls import ROUTER
from talklist.views import (TalkListCreateView, TalkListDetailView, TalkListListView, TalkListScheduleView,
                            TalkListUpdateView, TalkListViewSet)

app_name = 'talklists'

ROUTER.register(r'talk-lists', TalkListViewSet, base_name='talklist')

urlpatterns = [
    path('', TalkListListView.as_view(), name='list'),
    path('create/', TalkListCreateView.as_view(), name='create'),
    path('<slug:slug>/detail/', TalkListDetailView.as_view(), name='detail'),
    path('<slug:slug>/update/', TalkListUpdateView.as_view(), name='update'),
    path('<slug:slug>/schedule/', TalkListScheduleView.as_view(), name='schedule'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/templates/_layouts/base.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="yandex-verification" content="ddd62f07e2144baf" />
    <title>{% block title %}{% endblock %} :: Django Survival Guide</title>

    {%  render_bundle "main" %}
    {%  render_bundle "vendor" %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <header>{% include '_layouts/navbar.html' %}</header>

    <div class="container theme-showcase" role="main">
        {% block headline %}{% endblock %}

        {% if messages %}
        <div>
            <ul class="list-unstyled messages">
                {% for message in messages %}
                <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {% block content %}{% endblock %}

        {% block styles %}{% endblock %}
    </div>
</body>
</html>

src/templates/_layouts/navbar.html
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">PyCon Survival Guide</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            {% url 'talklists:list' as list %}
            {% if request.user.is_authenticated %}
                <li {% if request.path == list %} class="active" {% endif %}><a href="{% url 'talklists:list' %}">Talk Lists</a></li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'talklists:create' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Create a new list
                    </a>
                </li>
            {% endif %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  {% if user.is_authenticated %}Hello, {{ user.username }}{% else %}Account{% endif %} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                  {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'account_logout' %}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;Logout
                        </a>
                    </li>
                  {% else %}
                    <li>
                        <a href="{% url 'account_login' %}">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;Login
                        </a>
                    </li>
                    <li><a href="{% url 'account_signup' %}">Signup</a></li>
                  {% endif %}
              </ul>
            </li>
        </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>